# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e16da303c740ef845e03eaffa12ba776cce15599fe2500275d2090daa66ace4b3e1f2ecc9aa1927a09579f2e9f5cecbefe959fa87c84c089c4bbba8d84eed7

test:
  secret_key_base: 84dce9bd5d320dc41a26f5a614473f7f7ab8b290315226c9c7f3439176ae6cfc5429ac7d5ad56f885feea2a70af1879db9cc2b4a59937c3415f44c1398dcb369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
